from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
urlpatterns=[
    path('',views.index,name='index'),
    path('vac',views.vac,name='vac'),
    path('vacc2',views.vaccn,name='vacc2'),
    path('news-detail',views.news,name='news-detail'),
    path('revisitvac',views.revisitvac,name='revisitvac'),
    
    path('blood',views.bloods,name='blood'),
    path('job',views.jobs,name='job'),
    path('load',views.load,name='load'),
    path('managevac',views.managevac,name='managevac'),
    path('add_vac',views.add_vac,name='add_vac'),
    path('edit_vac/<str:sid>/',views.edit_vac,name='edit_vac'),
    path('del_vac/<str:sid>/',views.del_vac,name='del_vac'),
    path('success',views.success,name='success'),
    path('addsuccess',views.addsuccess,name='addsuccess'),
    path('doctorapp',views.doctorapp,name='doctorapp'),
    path('notpatient',views.notpatient,name='notpatient'),

    path('page_login',views.pagelogin,name='page_login'),
    path('admin_index',views.adminindex,name='admin_index'),
    path('page-forgot-password',views.pageforget,name='page-forgot-password'),
   # path('page-register',views.pagereg,name='page-register'),
#path('patient',views.patient,name='patient'),
#path('patient-details',views.patientd,name='patient-details'),
    #path('doctor',views.doctor,name='doctor'),
    path('doctor-details',views.doctordetails,name='doctor-details'),
    path('reviews',views.reviews,name='reviews'),
    path('email-compose/<str:sid>/',views.emailcompose,name='email-compose'),
    path('email-inbox',views.emailinbox,name='email-inbox'),
    path('email-read',views.emailread,name='email-read'),
    path('chart-flot',views.chartflot,name='chart-flot'),
    path('chart-morris',views.chartmorris,name='chart-morris'),
    path('chart-chartjs',views.chartchartjs,name='chart-chartjs'),
    path('chart-chartist',views.chartchartist,name='chart-chartist'),
    path('chart-sparkline',views.chartsparkline,name='chart-sparkline'),
    path('chart-peity',views.chartpeity,name='chart-peity'),
    path('patientdis',views.patientdis,name='patientdis'),
    path('generateinpatientbills/<str:id>/',views.generateinpatientbills,name='generateinpatientbills'),
    path('print_inpatientbills/<str:sid>/',views.print_inpatientbills,name='print_inpatientbills'),
    path('uploadfile',views.uploadfile,name='uploadfile'),
    path('sendbills',views.sendbills,name='sendbills'),
    path('uploadreportfile',views.uploadreportfile,name='uploadreportfile'),
    path('sendreports',views.sendreports,name='sendreports'),
    path('email-compose2/<str:sid>/',views.emailcompose2,name='email-compose2'),
    path('vac',views.vac,name='vac'),
    path('vacc2',views.vaccn,name='vacc2'),
    path('doctorapp',views.doctorapp,name='doctorapp'),
    path('revisitdc',views.revisitdc,name='revisitdc'),
    path('appoinmentsuccessfull',views.appsucc,name='appoinmentsuccessfull'),
    path('revisitdetails',views.revisitdetails,name='revisitdetails'),
    path('vaccsuccessfull',views.vaccsuccessfull,name='vaccsuccessfull'),
    path('successfullreappoinment',views.successfullre,name='successfullreappoinment'),
    path('successfull',views.successfull,name='successfull'),
    path('managestatus',views.managestatus,name='managestatus'),
    path('inpatient',views.inpatient,name='inpatient'),
    path('inpatientdisplay',views.inpatientdisplay,name='inpatientdisplay'),
    path('outpatient',views.outpatient,name='outpatient'),
    path('outpaitentdisplay',views.outpatientdisplay,name='outpatientdisplay'),
    path('date1',views.date1,name='date1'),
    path('datefetch',views.datefetch,name='datefetch'),
    path('fromdate',views.fromdate,name='fromdate'),
    path('displaydatedetails',views.displaydatedetails,name='displaydatedetails'),
    path('todate',views.todate,name='todate'),
    path('ridwise',views.ridwise,name='ridwise'),
    path('single',views.single,name='single'),
    path('singledetails',views.singledetails,name='singledetails'),
    path('datein',views.datein,name='datein'),
    path('datewisein',views.datewisein,name='datewisein'),
    path('dataindetails',views.dataindetails,name='dataindetails'),
    path('datewiseout',views.datewiseout,name='datewiseout'),
    path('dateout',views.dateout,name='dateout'),
    path('dataoutdetails',views.dataoutdetails,name='dataoutdetails'),
    path('printdis',views.printdis,name='printdis'),
    path('uploadfilesuccess',views.uploadfilesuccess,name='uploadfilesuccess'),
    path('reportsuccess',views.reportsuccess,name='reportsuccess'),
    path('managejob',views.managejob,name='managejob'),
    path('addjob',views.addjob,name='addjob'),
    path('jobadding',views.jobadding,name='jobadding'),
    path('addsuccessjob',views.addsuccessjob,name='addsuccessjob'),
    path('editjob/<str:jid>/',views.editjob,name='editjob'),
    path('jobedittedsuccessfull',views.jobedittedsuccessfull,name='jobedittedsuccessfull'),
    path('deljob/<str:jid>/',views.deljob,name='deljob'),
    path('jobdelsuccessfull',views.jobdelsuccessfull,name='jobdelsuccessfull'),
    path('changepwd/',views.changepwd,name='changepwd'),
    path('reportvacsuccesful',views.reportvacsuccesful,name='reportvacsuccesful'),
    path('uploadvacreport',views.uploadvacreport,name='uploadvacreport'),
    path('patientvacdis',views.patientvacdis,name='patientvacdis'),
    path('printvacreport/<str:id>,<str:rid>,<str:aid>/',views.printvacreport,name='printvacreport'),
    path('printvacdis',views.printvacdis,name='printvacdis'),
    path('generatevacbills/<str:id>/',views.generatevacbills,name='generatevacbills'),
    path('print_vacbills/<str:sid>/',views.print_vacbills,name='print_vacbills'),
    path('uploadvacbill',views.uploadvacbill,name='uploadvacbill'),
    path('uploadvacbillsuccess',views.uploadvacbillsuccess,name='uploadvacbillsuccess'),
    path('sendvacbill',views.sendvacbill,name='sendvacbill'),
    path('email_composevac/<str:sid>/',views.email_composevac,name='email_composevac'),
    path('vacreportdis',views.vacreportdis,name='vacreportdis'),
    path('sendvacreport',views.sendvacreport,name='sendvacreport'),
    path('email_composevac2/<str:sid>/',views.email_composevac2,name='email_composevac2'),
    path('pageforgetemailsuc',views.pageforgetemailsuc,name='pageforgetemailsuc'),
    path('removebloodsuccess/<str:sno>/',views.removebloodsuccess,name='removebloodsuccess'),
    path('removejobuser?<str:sno>',views.removejobuser,name='removejobuser'),
    path('bloodsuccess',views.bloodsuccess,name='bloodsuccess'),
    path('removeuser/<str:id>,<str:rid>,<str:aid>/',views.removeuser,name='removeuser'),
    path('jobsuccess',views.jobsuccess,name='jobsuccess'),







    

   # path('#about',views.about,name='#about'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)